apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:openshift-controller-manager:deployer-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:openshift-controller-manager:deployer-controller
subjects:
- kind: ServiceAccount
  name: deployer-controller
  namespace: openshift-infra
