apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:openshift-controller-manager:deploymentconfig-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:openshift-controller-manager:deploymentconfig-controller
subjects:
- kind: ServiceAccount
  name: deploymentconfig-controller
  namespace: openshift-infra
