apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:controller:serviceaccount-pull-secrets-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:controller:serviceaccount-pull-secrets-controller
subjects:
- kind: ServiceAccount
  name: serviceaccount-pull-secrets-controller
  namespace: openshift-infra
