apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:controller:template-instance-finalizer-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:controller:template-instance-finalizer-controller
subjects:
- kind: ServiceAccount
  name: template-instance-finalizer-controller
  namespace: openshift-infra
